--// setup.sql
--//
--// Paul Symansky, copyright 2012
--//
--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--// GPLv3 License
--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--//
--//    This file is part of Barcode USPS Shipping.
--//
--//    Barcode USPS Shipping is free software: you can redistribute it and/or modify
--//    it under the terms of the GNU General Public License as published by
--//    the Free Software Foundation, either version 3 of the License, or
--//    (at your option) any later version.
--//
--//    Barcode USPS Shipping is distributed in the hope that it will be useful,
--//    but WITHOUT ANY WARRANTY; without even the implied warranty of
--//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--//    GNU General Public License for more details.
--//
--//    You should have received a copy of the GNU General Public License
--//    along with Barcode USPS Shipping.  If not, see <http://www.gnu.org/licenses/>.
--//
--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


-- Table structures
DROP TABLE IF EXISTS `bc_states`;
CREATE TABLE `bc_states` (
  `state_code` varchar(2) collate latin1_german2_ci NOT NULL,
  `state` varchar(128) collate latin1_german2_ci NOT NULL,
  UNIQUE KEY `state_code` (`state_code`),
  FULLTEXT KEY `state` (`state`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci;

DROP TABLE IF EXISTS `bc_countries`;
CREATE TABLE `bc_countries` (
  `old_usps_country_code` varchar(5) collate latin1_german2_ci NOT NULL,
  `new_usps_country_code` varchar(3) collate latin1_german2_ci NOT NULL,
  `iso_country_code` varchar(6) collate latin1_german2_ci NOT NULL,
  `country` varchar(128) collate latin1_german2_ci NOT NULL,
  UNIQUE KEY `country_code` (`old_usps_country_code`),
  FULLTEXT KEY `country` (`country`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci;


-- Table data
INSERT INTO bc_states (state_code, state) VALUES ('AL', 'ALABAMA');
INSERT INTO bc_states (state_code, state) VALUES ('AK', 'ALASKA');
INSERT INTO bc_states (state_code, state) VALUES ('AS', 'AMERICAN SAMOA');
INSERT INTO bc_states (state_code, state) VALUES ('AZ', 'ARIZONA');
INSERT INTO bc_states (state_code, state) VALUES ('AR', 'ARKANSAS');
INSERT INTO bc_states (state_code, state) VALUES ('CA', 'CALIFORNIA');
INSERT INTO bc_states (state_code, state) VALUES ('CO', 'COLORADO');
INSERT INTO bc_states (state_code, state) VALUES ('CT', 'CONNECTICUT');
INSERT INTO bc_states (state_code, state) VALUES ('DE', 'DELAWARE');
INSERT INTO bc_states (state_code, state) VALUES ('DC', 'DISTRICT OF COLUMBIA');
INSERT INTO bc_states (state_code, state) VALUES ('FL', 'FLORIDA');
INSERT INTO bc_states (state_code, state) VALUES ('GA', 'GEORGIA');
INSERT INTO bc_states (state_code, state) VALUES ('GU', 'GUAM');
INSERT INTO bc_states (state_code, state) VALUES ('HI', 'HAWAII');
INSERT INTO bc_states (state_code, state) VALUES ('ID', 'IDAHO');
INSERT INTO bc_states (state_code, state) VALUES ('IL', 'ILLINOIS');
INSERT INTO bc_states (state_code, state) VALUES ('IN', 'INDIANA');
INSERT INTO bc_states (state_code, state) VALUES ('IA', 'IOWA');
INSERT INTO bc_states (state_code, state) VALUES ('KS', 'KANSAS');
INSERT INTO bc_states (state_code, state) VALUES ('KY', 'KENTUCKY');
INSERT INTO bc_states (state_code, state) VALUES ('LA', 'LOUISIANA');
INSERT INTO bc_states (state_code, state) VALUES ('ME', 'MAINE');
INSERT INTO bc_states (state_code, state) VALUES ('MH', 'MARSHALL ISLANDS');
INSERT INTO bc_states (state_code, state) VALUES ('MD', 'MARYLAND');
INSERT INTO bc_states (state_code, state) VALUES ('MA', 'MASSACHUSETTS');
INSERT INTO bc_states (state_code, state) VALUES ('MI', 'MICHIGAN');
INSERT INTO bc_states (state_code, state) VALUES ('FM', 'MICRONESIA');
INSERT INTO bc_states (state_code, state) VALUES ('MN', 'MINNESOTA');
INSERT INTO bc_states (state_code, state) VALUES ('MS', 'MISSISSIPPI');
INSERT INTO bc_states (state_code, state) VALUES ('MO', 'MISSOURI');
INSERT INTO bc_states (state_code, state) VALUES ('MT', 'MONTANA');
INSERT INTO bc_states (state_code, state) VALUES ('NE', 'NEBRASKA');
INSERT INTO bc_states (state_code, state) VALUES ('NV', 'NEVADA');
INSERT INTO bc_states (state_code, state) VALUES ('NH', 'NEW HAMPSHIRE');
INSERT INTO bc_states (state_code, state) VALUES ('NJ', 'NEW JERSEY');
INSERT INTO bc_states (state_code, state) VALUES ('NM', 'NEW MEXICO');
INSERT INTO bc_states (state_code, state) VALUES ('NY', 'NEW YORK');
INSERT INTO bc_states (state_code, state) VALUES ('NC', 'NORTH CAROLINA');
INSERT INTO bc_states (state_code, state) VALUES ('ND', 'NORTH DAKOTA');
INSERT INTO bc_states (state_code, state) VALUES ('MP', 'NORTH MARIANA ISLANDS');
INSERT INTO bc_states (state_code, state) VALUES ('OH', 'OHIO');
INSERT INTO bc_states (state_code, state) VALUES ('OK', 'OKLAHOMA');
INSERT INTO bc_states (state_code, state) VALUES ('OR', 'OREGON');
INSERT INTO bc_states (state_code, state) VALUES ('PW', 'PALAU');
INSERT INTO bc_states (state_code, state) VALUES ('PA', 'PENNSYLVANIA');
INSERT INTO bc_states (state_code, state) VALUES ('PR', 'PUERTO RICO');
INSERT INTO bc_states (state_code, state) VALUES ('RI', 'RHODE ISLAND');
INSERT INTO bc_states (state_code, state) VALUES ('SC', 'SOUTH CAROLINA');
INSERT INTO bc_states (state_code, state) VALUES ('SD', 'SOUTH DAKOTA');
INSERT INTO bc_states (state_code, state) VALUES ('TN', 'TENNESSEE');
INSERT INTO bc_states (state_code, state) VALUES ('TX', 'TEXAS');
INSERT INTO bc_states (state_code, state) VALUES ('UT', 'UTAH');
INSERT INTO bc_states (state_code, state) VALUES ('VI', 'VIRGIN ISLANDS');
INSERT INTO bc_states (state_code, state) VALUES ('VA', 'VIRGINIA');
INSERT INTO bc_states (state_code, state) VALUES ('VT', 'VERMONT');
INSERT INTO bc_states (state_code, state) VALUES ('WA', 'WASHINGTON');
INSERT INTO bc_states (state_code, state) VALUES ('WV', 'WEST VIRGINIA');
INSERT INTO bc_states (state_code, state) VALUES ('WI', 'WISCONSIN');
INSERT INTO bc_states (state_code, state) VALUES ('WY', 'WYOMING');
INSERT INTO bc_states (state_code, state) VALUES ('AA', 'AA');
INSERT INTO bc_states (state_code, state) VALUES ('AE', 'AE');
INSERT INTO bc_states (state_code, state) VALUES ('AP', 'AP');

INSERT INTO `bc_countries` VALUES ('10003', '20', 'AD', 'Andorra');
INSERT INTO `bc_countries` VALUES ('10446', '784', 'AE', 'Trucial States');
INSERT INTO `bc_countries` VALUES ('10441', '784', 'AE-AJ', 'Ajman');
INSERT INTO `bc_countries` VALUES ('10440', '784', 'AE-AZ', 'Abu Dhabi');
INSERT INTO `bc_countries` VALUES ('10442', '784', 'AE-DU', 'Dubai');
INSERT INTO `bc_countries` VALUES ('10443', '784', 'AE-FU', 'Fujairah');
INSERT INTO `bc_countries` VALUES ('10444', '784', 'AE-RK', 'Ras al Kaimah');
INSERT INTO `bc_countries` VALUES ('10445', '784', 'AE-SH', 'Sharja');
INSERT INTO `bc_countries` VALUES ('10447', '784', 'AE-UQ', 'Umm al Quaiwain');
INSERT INTO `bc_countries` VALUES ('10000', '4', 'AF', 'Afghanistan');
INSERT INTO `bc_countries` VALUES ('12140', '28', 'AG', 'Antigua');
INSERT INTO `bc_countries` VALUES ('10006', '28', 'AG', 'Antigua and Barbuda');
INSERT INTO `bc_countries` VALUES ('10007', '28', 'AG', 'Barbuda');
INSERT INTO `bc_countries` VALUES ('10008', '28', 'AG', 'Redonda');
INSERT INTO `bc_countries` VALUES ('10005', '660', 'AI', 'Anguilla');
INSERT INTO `bc_countries` VALUES ('10001', '8', 'AL', 'Albania');
INSERT INTO `bc_countries` VALUES ('10010', '51', 'AM', 'Armenia');
INSERT INTO `bc_countries` VALUES ('10299', '530', 'AN', 'Bonaire');
INSERT INTO `bc_countries` VALUES ('10300', '530', 'AN', 'Curacao');
INSERT INTO `bc_countries` VALUES ('10301', '530', 'AN', 'Netherlands Antilles');
INSERT INTO `bc_countries` VALUES ('10302', '530', 'AN', 'Netherlands West Indies');
INSERT INTO `bc_countries` VALUES ('10303', '530', 'AN', 'Saba');
INSERT INTO `bc_countries` VALUES ('10304', '530', 'AN', 'Saint Eustatius');
INSERT INTO `bc_countries` VALUES ('10305', '530', 'AN', 'Saint Maarten');
INSERT INTO `bc_countries` VALUES ('10004', '24', 'AO', 'Angola');
INSERT INTO `bc_countries` VALUES ('10009', '32', 'AR', 'Argentina');
INSERT INTO `bc_countries` VALUES ('10026', '40', 'AT', 'Austria');
INSERT INTO `bc_countries` VALUES ('10013', '36', 'AU', 'Australia');
INSERT INTO `bc_countries` VALUES ('10226', '36', 'AU', 'Christmas Island');
INSERT INTO `bc_countries` VALUES ('10015', '166', 'AU', 'Cocos Island');
INSERT INTO `bc_countries` VALUES ('10016', '36', 'AU', 'Keeling Islands');
INSERT INTO `bc_countries` VALUES ('10017', '36', 'AU', 'Lord Howe Island');
INSERT INTO `bc_countries` VALUES ('10023', '36', 'AU', 'Thursday Island');
INSERT INTO `bc_countries` VALUES ('10448', '784', 'AE', 'United Arab Emirates');
INSERT INTO `bc_countries` VALUES ('10018', '36', 'AU-NS', 'New South Wales');
INSERT INTO `bc_countries` VALUES ('10020', '36', 'AU-QL', 'Queensland');
INSERT INTO `bc_countries` VALUES ('10021', '36', 'AU-SA', 'South Australia');
INSERT INTO `bc_countries` VALUES ('10022', '36', 'AU-TS', 'Tasmania');
INSERT INTO `bc_countries` VALUES ('10024', '36', 'AU-VI', 'Victoria');
INSERT INTO `bc_countries` VALUES ('10025', '36', 'AU-WA', 'Western Australia');
INSERT INTO `bc_countries` VALUES ('10011', '533', 'AW', 'Aruba');
INSERT INTO `bc_countries` VALUES ('10449', '858', 'AY', 'Uruguay');
INSERT INTO `bc_countries` VALUES ('10027', '31', 'AZ', 'Azerbaijan');
INSERT INTO `bc_countries` VALUES ('10041', '70', 'BA', 'Bosnia-Herzegovina');
INSERT INTO `bc_countries` VALUES ('10031', '52', 'BB', 'Barbados');
INSERT INTO `bc_countries` VALUES ('10030', '50', 'BD', 'Bangladesh');
INSERT INTO `bc_countries` VALUES ('10033', '56', 'BE', 'Belgium');
INSERT INTO `bc_countries` VALUES ('10047', '854', 'BF', 'Burkina Faso');
INSERT INTO `bc_countries` VALUES ('10046', '100', 'BG', 'Bulgaria');
INSERT INTO `bc_countries` VALUES ('10029', '48', 'BH', 'Bahrain');
INSERT INTO `bc_countries` VALUES ('10050', '108', 'BI', 'Burundi');
INSERT INTO `bc_countries` VALUES ('10036', '204', 'BJ', 'Benin');
INSERT INTO `bc_countries` VALUES ('10037', '204', 'BJ', 'Dahomey');
INSERT INTO `bc_countries` VALUES ('12019', '652', 'BL', 'Saint Barthelemy');
INSERT INTO `bc_countries` VALUES ('10038', '60', 'BM', 'Bermuda');
INSERT INTO `bc_countries` VALUES ('10045', '96', 'BN', 'Brunei Darussalam');
INSERT INTO `bc_countries` VALUES ('10040', '68', 'BO', 'Bolivia');
INSERT INTO `bc_countries` VALUES ('10043', '76', 'BR', 'Brazil');
INSERT INTO `bc_countries` VALUES ('10028', '44', 'BS', 'Bahamas');
INSERT INTO `bc_countries` VALUES ('10039', '64', 'BT', 'Bhutan');
INSERT INTO `bc_countries` VALUES ('10042', '72', 'BW', 'Botswana');
INSERT INTO `bc_countries` VALUES ('10032', '112', 'BY', 'Belarus');
INSERT INTO `bc_countries` VALUES ('10034', '84', 'BZ', 'Belize');
INSERT INTO `bc_countries` VALUES ('10035', '84', 'BZ', 'British Honduras');
INSERT INTO `bc_countries` VALUES ('12000', '124', 'CA', 'Alberta');
INSERT INTO `bc_countries` VALUES ('12001', '124', 'CA', 'British Columbia');
INSERT INTO `bc_countries` VALUES ('10054', '124', 'CA', 'Canada');
INSERT INTO `bc_countries` VALUES ('12006', '124', 'CA', 'Manitoba');
INSERT INTO `bc_countries` VALUES ('12011', '124', 'CA', 'New Brunswick');
INSERT INTO `bc_countries` VALUES ('12012', '124', 'CA', 'Northwest Territory');
INSERT INTO `bc_countries` VALUES ('12013', '124', 'CA', 'Nova Scotia');
INSERT INTO `bc_countries` VALUES ('12014', '124', 'CA', 'Ontario');
INSERT INTO `bc_countries` VALUES ('12015', '124', 'CA', 'Prince Edward Island');
INSERT INTO `bc_countries` VALUES ('12016', '124', 'CA', 'Quebec');
INSERT INTO `bc_countries` VALUES ('12018', '124', 'CA', 'Saskatchewan');
INSERT INTO `bc_countries` VALUES ('12024', '124', 'CA', 'Yukon Territory');
INSERT INTO `bc_countries` VALUES ('10055', '124', 'CA-NL', 'Labrador');
INSERT INTO `bc_countries` VALUES ('10056', '124', 'CA-NL', 'Newfoundland');
INSERT INTO `bc_countries` VALUES ('10073', '180', 'CD', 'Democratic Republic of the Congo');
INSERT INTO `bc_countries` VALUES ('10059', '140', 'CF', 'Central African Republic');
INSERT INTO `bc_countries` VALUES ('10072', '178', 'CG', 'Republic of the Congo');
INSERT INTO `bc_countries` VALUES ('10412', '756', 'CH', 'Switzerland');
INSERT INTO `bc_countries` VALUES ('10081', '384', 'CI', 'Cote d Ivoire');
INSERT INTO `bc_countries` VALUES ('12312', '384', 'CI', 'Ivory Coast');
INSERT INTO `bc_countries` VALUES ('10314', '184', 'CK', 'Aitutaki, Cook Islands');
INSERT INTO `bc_countries` VALUES ('12026', '184', 'CK', 'Atiu, Cook Islands');
INSERT INTO `bc_countries` VALUES ('10316', '184', 'CK', 'Cook Islands');
INSERT INTO `bc_countries` VALUES ('10318', '184', 'CK', 'Hervey, Cook Islands');
INSERT INTO `bc_countries` VALUES ('10327', '184', 'CK', 'Parry, Cook Islands');
INSERT INTO `bc_countries` VALUES ('10331', '184', 'CK', 'Rarotonga, Cook Islands');
INSERT INTO `bc_countries` VALUES ('10062', '152', 'CL', 'Chile');
INSERT INTO `bc_countries` VALUES ('10053', '120', 'CM', 'Cameroon');
INSERT INTO `bc_countries` VALUES ('10063', '156', 'CN', 'China');
INSERT INTO `bc_countries` VALUES ('10065', '156', 'CN', 'Manchuria');
INSERT INTO `bc_countries` VALUES ('10064', '156', 'CN-46', 'Hainan Island');
INSERT INTO `bc_countries` VALUES ('10066', '156', 'CN-54', 'Tibet');
INSERT INTO `bc_countries` VALUES ('10067', '170', 'CO', 'Colombia');
INSERT INTO `bc_countries` VALUES ('10080', '188', 'CR', 'Costa Rica');
INSERT INTO `bc_countries` VALUES ('10083', '192', 'CU', 'Cuba');
INSERT INTO `bc_countries` VALUES ('10084', '192', 'CU', 'Isle of Pines, West Indies');
INSERT INTO `bc_countries` VALUES ('10057', '132', 'CV', 'Cape Verde');
INSERT INTO `bc_countries` VALUES ('10085', '196', 'CY', 'Cyprus');
INSERT INTO `bc_countries` VALUES ('10086', '203', 'CZ', 'Czech Republic');
INSERT INTO `bc_countries` VALUES ('10137', '276', 'DE', 'Germany');
INSERT INTO `bc_countries` VALUES ('10088', '262', 'DJ', 'Djibouti');
INSERT INTO `bc_countries` VALUES ('10089', '262', 'DJ', 'French Somaliland');
INSERT INTO `bc_countries` VALUES ('10090', '262', 'DJ', 'French Territory of the Afars and Issas');
INSERT INTO `bc_countries` VALUES ('12077', '262', 'DJ', 'Issas');
INSERT INTO `bc_countries` VALUES ('10087', '208', 'DK', 'Denmark');
INSERT INTO `bc_countries` VALUES ('10091', '212', 'DM', 'Dominica');
INSERT INTO `bc_countries` VALUES ('10092', '214', 'DO', 'Dominican Republic');
INSERT INTO `bc_countries` VALUES ('10002', '12', 'DZ', 'Algeria');
INSERT INTO `bc_countries` VALUES ('10093', '218', 'EC', 'Ecuador');
INSERT INTO `bc_countries` VALUES ('10104', '233', 'EE', 'Estonia');
INSERT INTO `bc_countries` VALUES ('10094', '818', 'EG', 'Egypt');
INSERT INTO `bc_countries` VALUES ('10103', '232', 'ER', 'Eritrea');
INSERT INTO `bc_countries` VALUES ('10388', '724', 'ES', 'Alhucemas');
INSERT INTO `bc_countries` VALUES ('10392', '724', 'ES', 'Chaferinas Islands');
INSERT INTO `bc_countries` VALUES ('10394', '724', 'ES', 'Penon de Velez de la Gomera');
INSERT INTO `bc_countries` VALUES ('10395', '724', 'ES', 'Spain');
INSERT INTO `bc_countries` VALUES ('10396', '724', 'ES', 'Zafarani Islands');
INSERT INTO `bc_countries` VALUES ('10391', '724', 'ES-CE', 'Ceuta');
INSERT INTO `bc_countries` VALUES ('10390', '724', 'ES-CN', 'Canary Islands');
INSERT INTO `bc_countries` VALUES ('10393', '724', 'ES-ML', 'Melilla');
INSERT INTO `bc_countries` VALUES ('10389', '724', 'ES-PM', 'Balearic Islands');
INSERT INTO `bc_countries` VALUES ('10105', '231', 'ET', 'Ethiopia');
INSERT INTO `bc_countries` VALUES ('10110', '248', 'FI', 'Aland Island');
INSERT INTO `bc_countries` VALUES ('10111', '246', 'FI', 'Finland');
INSERT INTO `bc_countries` VALUES ('10109', '242', 'FJ', 'Fiji');
INSERT INTO `bc_countries` VALUES ('10106', '238', 'FK', 'Falkland Islands');
INSERT INTO `bc_countries` VALUES ('10457', '840', 'FM', 'Federated States of Micronesia');
INSERT INTO `bc_countries` VALUES ('10464', '840', 'FM', 'Kosrae, Micronesia');
INSERT INTO `bc_countries` VALUES ('10108', '234', 'FO', 'Faroe Islands');
INSERT INTO `bc_countries` VALUES ('10112', '250', 'FR', 'Corsica');
INSERT INTO `bc_countries` VALUES ('10113', '250', 'FR', 'France');
INSERT INTO `bc_countries` VALUES ('10116', '492', 'FR', 'Monaco');
INSERT INTO `bc_countries` VALUES ('10134', '266', 'GA', 'Gabon');
INSERT INTO `bc_countries` VALUES ('10140', '826', 'GB', 'Alderney');
INSERT INTO `bc_countries` VALUES ('10012', '826', 'GB', 'Ascension');
INSERT INTO `bc_countries` VALUES ('10141', '826', 'GB', 'Channel Islands (Jersey, Guernsey, Alderney and Sark)');
INSERT INTO `bc_countries` VALUES ('10143', '826', 'GB', 'Great Britain and Northern Ireland');
INSERT INTO `bc_countries` VALUES ('10147', '826', 'GB', 'Northern Ireland');
INSERT INTO `bc_countries` VALUES ('10430', '826', 'GB', 'Tristan da Cunha');
INSERT INTO `bc_countries` VALUES ('10150', '826', 'GB', 'United Kingdom');
INSERT INTO `bc_countries` VALUES ('10142', '826', 'GB-ENG', 'England');
INSERT INTO `bc_countries` VALUES ('10144', '831', 'GB-GSY', 'Guernsey');
INSERT INTO `bc_countries` VALUES ('10145', '833', 'GB-IOM', 'Isle of Man');
INSERT INTO `bc_countries` VALUES ('10146', '832', 'GB-JSY', 'Jersey');
INSERT INTO `bc_countries` VALUES ('10149', '826', 'GB-SCT', 'Scotland');
INSERT INTO `bc_countries` VALUES ('10151', '826', 'GB-WLS', 'Wales');
INSERT INTO `bc_countries` VALUES ('10170', '308', 'GD', 'Grenada');
INSERT INTO `bc_countries` VALUES ('10136', '268', 'GE', 'Republic of Georgia');
INSERT INTO `bc_countries` VALUES ('10117', '254', 'GF', 'French Guiana');
INSERT INTO `bc_countries` VALUES ('10138', '288', 'GH', 'Ghana');
INSERT INTO `bc_countries` VALUES ('10139', '292', 'GI', 'Gibraltar');
INSERT INTO `bc_countries` VALUES ('10169', '304', 'GL', 'Greenland');
INSERT INTO `bc_countries` VALUES ('10135', '270', 'GM', 'Gambia');
INSERT INTO `bc_countries` VALUES ('10182', '324', 'GN', 'Guinea');
INSERT INTO `bc_countries` VALUES ('10171', '312', 'GP', 'Barthelemy');
INSERT INTO `bc_countries` VALUES ('10172', '312', 'GP', 'Desirade Island');
INSERT INTO `bc_countries` VALUES ('12002', '312', 'GP', 'French West Indies');
INSERT INTO `bc_countries` VALUES ('10174', '312', 'GP', 'Guadeloupe');
INSERT INTO `bc_countries` VALUES ('10175', '312', 'GP', 'Les Saints Island');
INSERT INTO `bc_countries` VALUES ('10176', '312', 'GP', 'Marie Galante');
INSERT INTO `bc_countries` VALUES ('10177', '312', 'GP', 'Petite Terre');
INSERT INTO `bc_countries` VALUES ('10178', '312', 'GP', 'Saint Bartholomew');
INSERT INTO `bc_countries` VALUES ('10179', '663', 'GP', 'Saint Martin');
INSERT INTO `bc_countries` VALUES ('10097', '226', 'GQ', 'Annobon Island');
INSERT INTO `bc_countries` VALUES ('10098', '226', 'GQ', 'Corisco Island');
INSERT INTO `bc_countries` VALUES ('10099', '226', 'GQ', 'Elobey Islands');
INSERT INTO `bc_countries` VALUES ('10100', '226', 'GQ', 'Equatorial Guinea');
INSERT INTO `bc_countries` VALUES ('10101', '226', 'GQ', 'Fernando Po');
INSERT INTO `bc_countries` VALUES ('10102', '226', 'GQ', 'Rio Muni');
INSERT INTO `bc_countries` VALUES ('10154', '300', 'GR', 'Crete');
INSERT INTO `bc_countries` VALUES ('10156', '300', 'GR', 'Greece');
INSERT INTO `bc_countries` VALUES ('10152', '300', 'GR-81', 'Astypalaia');
INSERT INTO `bc_countries` VALUES ('10153', '300', 'GR-81', 'Chalki');
INSERT INTO `bc_countries` VALUES ('10155', '300', 'GR-81', 'Dodecanese Islands');
INSERT INTO `bc_countries` VALUES ('10157', '300', 'GR-81', 'Kalymnos');
INSERT INTO `bc_countries` VALUES ('10158', '300', 'GR-81', 'Karpathos');
INSERT INTO `bc_countries` VALUES ('10159', '300', 'GR-81', 'Kassos');
INSERT INTO `bc_countries` VALUES ('10160', '300', 'GR-81', 'Kastellorizon');
INSERT INTO `bc_countries` VALUES ('10161', '300', 'GR-81', 'Kos');
INSERT INTO `bc_countries` VALUES ('10162', '300', 'GR-81', 'Leipsos');
INSERT INTO `bc_countries` VALUES ('10163', '300', 'GR-81', 'Leros');
INSERT INTO `bc_countries` VALUES ('10164', '300', 'GR-81', 'Nissiros');
INSERT INTO `bc_countries` VALUES ('10165', '300', 'GR-81', 'Patmos');
INSERT INTO `bc_countries` VALUES ('10166', '300', 'GR-81', 'Rodos');
INSERT INTO `bc_countries` VALUES ('10167', '300', 'GR-81', 'Symi');
INSERT INTO `bc_countries` VALUES ('10168', '300', 'GR-81', 'Tilos');
INSERT INTO `bc_countries` VALUES ('10107', '239', 'GS', 'South Georgia');
INSERT INTO `bc_countries` VALUES ('10181', '320', 'GT', 'Guatemala');
INSERT INTO `bc_countries` VALUES ('10183', '624', 'GW', 'Guinea-Bissau');
INSERT INTO `bc_countries` VALUES ('10184', '328', 'GY', 'British Guiana');
INSERT INTO `bc_countries` VALUES ('10185', '328', 'GY', 'Guyana');
INSERT INTO `bc_countries` VALUES ('10189', '344', 'HK', 'Hong Kong');
INSERT INTO `bc_countries` VALUES ('10190', '344', 'HK', 'Kowloon');
INSERT INTO `bc_countries` VALUES ('10187', '340', 'HN', 'Honduras');
INSERT INTO `bc_countries` VALUES ('10188', '340', 'HN', 'Swan Islands');
INSERT INTO `bc_countries` VALUES ('10082', '191', 'HR', 'Croatia');
INSERT INTO `bc_countries` VALUES ('10186', '332', 'HT', 'Haiti');
INSERT INTO `bc_countries` VALUES ('10191', '348', 'HU', 'Hungary');
INSERT INTO `bc_countries` VALUES ('10200', '360', 'ID', 'Borneo');
INSERT INTO `bc_countries` VALUES ('10202', '360', 'ID', 'Indonesia');
INSERT INTO `bc_countries` VALUES ('10205', '360', 'ID', 'West New Guinea');
INSERT INTO `bc_countries` VALUES ('10203', '360', 'ID-IJ', 'Irian Barat');
INSERT INTO `bc_countries` VALUES ('10204', '360', 'ID-NT', 'Timor');
INSERT INTO `bc_countries` VALUES ('10209', '372', 'IE', 'Eire');
INSERT INTO `bc_countries` VALUES ('10210', '372', 'IE', 'Ireland');
INSERT INTO `bc_countries` VALUES ('10211', '376', 'IL', 'Israel');
INSERT INTO `bc_countries` VALUES ('10193', '356', 'IN-AN', 'Andaman Islands');
INSERT INTO `bc_countries` VALUES ('10194', '356', 'IN-DD', 'Damao');
INSERT INTO `bc_countries` VALUES ('10195', '356', 'IN-DD', 'Diu');
INSERT INTO `bc_countries` VALUES ('10196', '356', 'IN-GA', 'Goa');
INSERT INTO `bc_countries` VALUES ('10197', '356', 'IN-GA', 'India');
INSERT INTO `bc_countries` VALUES ('10198', '356', 'IN-SK', 'Sikkim');
INSERT INTO `bc_countries` VALUES ('10208', '368', 'IQ', 'Iraq');
INSERT INTO `bc_countries` VALUES ('10206', '364', 'IR', 'Iran');
INSERT INTO `bc_countries` VALUES ('10207', '364', 'IR', 'Persia');
INSERT INTO `bc_countries` VALUES ('10192', '352', 'IS', 'Iceland');
INSERT INTO `bc_countries` VALUES ('10212', '380', 'IT', 'Italy');
INSERT INTO `bc_countries` VALUES ('10213', '388', 'JM', 'Jamaica');
INSERT INTO `bc_countries` VALUES ('10220', '400', 'JO', 'Hashemite Kingdom');
INSERT INTO `bc_countries` VALUES ('10221', '400', 'JO', 'Jordan');
INSERT INTO `bc_countries` VALUES ('10222', '400', 'JO', 'Trans-Jordan, Hashemite Kingdom');
INSERT INTO `bc_countries` VALUES ('10214', '392', 'JP', 'Japan');
INSERT INTO `bc_countries` VALUES ('10215', '392', 'JP', 'Nansil Islands');
INSERT INTO `bc_countries` VALUES ('10218', '392', 'JP', 'Shikoku');
INSERT INTO `bc_countries` VALUES ('10219', '392', 'JP', 'Tori Shima');
INSERT INTO `bc_countries` VALUES ('10217', '392', 'JP-47', 'Okinawa');
INSERT INTO `bc_countries` VALUES ('10224', '404', 'KE', 'Kenya');
INSERT INTO `bc_countries` VALUES ('10237', '417', 'KG', 'Kyrgyzstan');
INSERT INTO `bc_countries` VALUES ('10051', '116', 'KH', 'Cambodia');
INSERT INTO `bc_countries` VALUES ('10052', '116', 'KH', 'Kampuchea');
INSERT INTO `bc_countries` VALUES ('10225', '296', 'KI', 'Canton Island');
INSERT INTO `bc_countries` VALUES ('10014', '162', 'KI', 'Christmas Island');
INSERT INTO `bc_countries` VALUES ('10227', '296', 'KI', 'Enderbury Island');
INSERT INTO `bc_countries` VALUES ('10228', '296', 'KI', 'Fanning Island');
INSERT INTO `bc_countries` VALUES ('10229', '296', 'KI', 'Gilbert Islands');
INSERT INTO `bc_countries` VALUES ('10230', '296', 'KI', 'Kiribati');
INSERT INTO `bc_countries` VALUES ('10231', '296', 'KI', 'Ocean Island');
INSERT INTO `bc_countries` VALUES ('10068', '174', 'KM', 'Anjouan');
INSERT INTO `bc_countries` VALUES ('10069', '174', 'KM', 'Comoros');
INSERT INTO `bc_countries` VALUES ('10070', '174', 'KM', 'Grand Comoro');
INSERT INTO `bc_countries` VALUES ('10071', '174', 'KM', 'Moheli');
INSERT INTO `bc_countries` VALUES ('10399', '659', 'KN', 'Nevis');
INSERT INTO `bc_countries` VALUES ('10400', '659', 'KN', 'Saint Christopher and Nevis');
INSERT INTO `bc_countries` VALUES ('10401', '659', 'KN', 'Saint Kitts');
INSERT INTO `bc_countries` VALUES ('10232', '408', 'KP', 'Democratic Peoples Republic of Korea');
INSERT INTO `bc_countries` VALUES ('10234', '410', 'KR', 'Republic of Korea');
INSERT INTO `bc_countries` VALUES ('10235', '410', 'KR', 'South Korea (Republic of Korea)');
INSERT INTO `bc_countries` VALUES ('10236', '414', 'KW', 'Kuwait');
INSERT INTO `bc_countries` VALUES ('10058', '136', 'KY', 'Cayman Islands');
INSERT INTO `bc_countries` VALUES ('10223', '398', 'KZ', 'Kazakhstan');
INSERT INTO `bc_countries` VALUES ('10238', '418', 'LA', 'Laos');
INSERT INTO `bc_countries` VALUES ('10240', '422', 'LB', 'Lebanon');
INSERT INTO `bc_countries` VALUES ('10403', '662', 'LC', 'Saint Lucia');
INSERT INTO `bc_countries` VALUES ('10247', '438', 'LI', 'Liechtenstein');
INSERT INTO `bc_countries` VALUES ('10397', '144', 'LK', 'Ceylon');
INSERT INTO `bc_countries` VALUES ('10398', '144', 'LK', 'Sri Lanka');
INSERT INTO `bc_countries` VALUES ('10242', '430', 'LR', 'Liberia');
INSERT INTO `bc_countries` VALUES ('10241', '426', 'LS', 'Lesotho');
INSERT INTO `bc_countries` VALUES ('10248', '440', 'LT', 'Lithuania');
INSERT INTO `bc_countries` VALUES ('10249', '442', 'LU', 'Luxembourg');
INSERT INTO `bc_countries` VALUES ('10239', '428', 'LV', 'Latvia');
INSERT INTO `bc_countries` VALUES ('10243', '434', 'LY', 'Cyjrenaica');
INSERT INTO `bc_countries` VALUES ('10244', '434', 'LY', 'Fezzan');
INSERT INTO `bc_countries` VALUES ('10245', '434', 'LY', 'Libya');
INSERT INTO `bc_countries` VALUES ('10246', '434', 'LY', 'Tripolitania');
INSERT INTO `bc_countries` VALUES ('10291', '504', 'MA', 'Morocco');
INSERT INTO `bc_countries` VALUES ('10288', '498', 'MD', 'Moldova');
INSERT INTO `bc_countries` VALUES ('12313', '499', 'ME', 'Montenegro');
INSERT INTO `bc_countries` VALUES ('10253', '450', 'MG', 'Madagascar');
INSERT INTO `bc_countries` VALUES ('10254', '450', 'MG', 'Malagasy Republic');
INSERT INTO `bc_countries` VALUES ('12017', '450', 'MG', 'Sainte Marie de Madagascar');
INSERT INTO `bc_countries` VALUES ('10252', '807', 'MK', 'Republic of Macedonia');
INSERT INTO `bc_countries` VALUES ('10279', '466', 'ML', 'Mali');
INSERT INTO `bc_countries` VALUES ('10048', '104', 'MM', 'Burma');
INSERT INTO `bc_countries` VALUES ('10049', '104', 'MM', 'Myanmar');
INSERT INTO `bc_countries` VALUES ('10289', '496', 'MN', 'Mongolia');
INSERT INTO `bc_countries` VALUES ('10250', '446', 'MO', 'Macao');
INSERT INTO `bc_countries` VALUES ('10251', '446', 'MO', 'Macau');
INSERT INTO `bc_countries` VALUES ('10173', '446', 'MQ', 'French West Indies');
INSERT INTO `bc_countries` VALUES ('10283', '474', 'MQ', 'Martinique');
INSERT INTO `bc_countries` VALUES ('10284', '478', 'MR', 'Mauritania');
INSERT INTO `bc_countries` VALUES ('10290', '500', 'MS', 'Montserrat');
INSERT INTO `bc_countries` VALUES ('10280', '470', 'MT', 'Cumino Island');
INSERT INTO `bc_countries` VALUES ('10281', '470', 'MT', 'Gozo Island');
INSERT INTO `bc_countries` VALUES ('10282', '470', 'MT', 'Malta');
INSERT INTO `bc_countries` VALUES ('10285', '480', 'MU', 'Mauritius');
INSERT INTO `bc_countries` VALUES ('10286', '480', 'MU', 'Rodrigues');
INSERT INTO `bc_countries` VALUES ('10278', '462', 'MV', 'Maldives');
INSERT INTO `bc_countries` VALUES ('10256', '454', 'MW', 'Malawi');
INSERT INTO `bc_countries` VALUES ('10257', '454', 'MW', 'Nyasaland');
INSERT INTO `bc_countries` VALUES ('10287', '484', 'MX', 'Mexico');
INSERT INTO `bc_countries` VALUES ('10264', '458', 'MY', 'Malaya');
INSERT INTO `bc_countries` VALUES ('10265', '458', 'MY', 'Malaysia');
INSERT INTO `bc_countries` VALUES ('10267', '458', 'MY', 'North Borneo');
INSERT INTO `bc_countries` VALUES ('10272', '458', 'MY', 'Province Wellesley');
INSERT INTO `bc_countries` VALUES ('10259', '458', 'MY-01', 'Johore');
INSERT INTO `bc_countries` VALUES ('10260', '458', 'MY-02', 'Kedah');
INSERT INTO `bc_countries` VALUES ('10261', '458', 'MY-03', 'Kelantan');
INSERT INTO `bc_countries` VALUES ('10263', '458', 'MY-04', 'Malacca');
INSERT INTO `bc_countries` VALUES ('10266', '458', 'MY-05', 'Negri Sembilan');
INSERT INTO `bc_countries` VALUES ('10268', '458', 'MY-06', 'Pahang');
INSERT INTO `bc_countries` VALUES ('10269', '458', 'MY-07', 'Penang');
INSERT INTO `bc_countries` VALUES ('10277', '458', 'MY-07', 'Wellesley, Province');
INSERT INTO `bc_countries` VALUES ('10270', '458', 'MY-08', 'Perak');
INSERT INTO `bc_countries` VALUES ('10271', '458', 'MY-09', 'Perlis');
INSERT INTO `bc_countries` VALUES ('10275', '458', 'MY-10', 'Selangor');
INSERT INTO `bc_countries` VALUES ('10276', '458', 'MY-11', 'Trengganu');
INSERT INTO `bc_countries` VALUES ('10273', '458', 'MY-12', 'Sabah');
INSERT INTO `bc_countries` VALUES ('10274', '458', 'MY-13', 'Sarawak');
INSERT INTO `bc_countries` VALUES ('10262', '458', 'MY-15', 'Labuan');
INSERT INTO `bc_countries` VALUES ('10292', '508', 'MZ', 'Mozambique');
INSERT INTO `bc_countries` VALUES ('10293', '516', 'NA', 'Namibia');
INSERT INTO `bc_countries` VALUES ('10294', '516', 'NA', 'South-West Africa');
INSERT INTO `bc_countries` VALUES ('10309', '540', 'NC', 'Alofi Island');
INSERT INTO `bc_countries` VALUES ('10310', '540', 'NC', 'Huan Island');
INSERT INTO `bc_countries` VALUES ('10311', '540', 'NC', 'Isle of Pines');
INSERT INTO `bc_countries` VALUES ('10312', '540', 'NC', 'Loyalty Islands');
INSERT INTO `bc_countries` VALUES ('10313', '540', 'NC', 'New Caledonia');
INSERT INTO `bc_countries` VALUES ('10336', '562', 'NE', 'Niger');
INSERT INTO `bc_countries` VALUES ('10019', '574', 'NF', 'Norfolk Island');
INSERT INTO `bc_countries` VALUES ('10337', '566', 'NG', 'Nigeria');
INSERT INTO `bc_countries` VALUES ('10335', '558', 'NI', 'Nicaragua');
INSERT INTO `bc_countries` VALUES ('10297', '528', 'NL', 'Holland');
INSERT INTO `bc_countries` VALUES ('10298', '528', 'NL', 'Netherlands');
INSERT INTO `bc_countries` VALUES ('10338', '578', 'NO', 'Norway');
INSERT INTO `bc_countries` VALUES ('10339', '578', 'NO', 'Spitzbergen');
INSERT INTO `bc_countries` VALUES ('10296', '524', 'NP', 'Nepal');
INSERT INTO `bc_countries` VALUES ('10295', '520', 'NR', 'Nauru');
INSERT INTO `bc_countries` VALUES ('10325', '570', 'NU', 'Niue');
INSERT INTO `bc_countries` VALUES ('10332', '570', 'NU', 'Savage Island, Niue');
INSERT INTO `bc_countries` VALUES ('10315', '540', 'NZ', 'Avarua');
INSERT INTO `bc_countries` VALUES ('10317', '540', 'NZ', 'Danger Islands');
INSERT INTO `bc_countries` VALUES ('10319', '540', 'NZ', 'Manahiki');
INSERT INTO `bc_countries` VALUES ('10324', '540', 'NZ', 'New Zealand');
INSERT INTO `bc_countries` VALUES ('10326', '540', 'NZ', 'Palmerston, Avarua');
INSERT INTO `bc_countries` VALUES ('10328', '540', 'NZ', 'Penrhyn, Tongareva');
INSERT INTO `bc_countries` VALUES ('10329', '540', 'NZ', 'Pukapuka');
INSERT INTO `bc_countries` VALUES ('10330', '540', 'NZ', 'Rakaanga');
INSERT INTO `bc_countries` VALUES ('10333', '540', 'NZ', 'Suwarrow Islands');
INSERT INTO `bc_countries` VALUES ('10334', '540', 'NZ', 'Tongareva');
INSERT INTO `bc_countries` VALUES ('10340', '512', 'OM', 'Muscat');
INSERT INTO `bc_countries` VALUES ('10341', '512', 'OM', 'Oman');
INSERT INTO `bc_countries` VALUES ('10344', '591', 'PA', 'Panama');
INSERT INTO `bc_countries` VALUES ('10354', '604', 'PE', 'Peru');
INSERT INTO `bc_countries` VALUES ('10118', '258', 'PF', 'Borabora');
INSERT INTO `bc_countries` VALUES ('10119', '258', 'PF', 'French Oceania');
INSERT INTO `bc_countries` VALUES ('10120', '258', 'PF', 'French Polynesia');
INSERT INTO `bc_countries` VALUES ('10121', '258', 'PF', 'Gambier');
INSERT INTO `bc_countries` VALUES ('10122', '258', 'PF', 'Hivaoa');
INSERT INTO `bc_countries` VALUES ('10123', '258', 'PF', 'Huahine');
INSERT INTO `bc_countries` VALUES ('10124', '258', 'PF', 'Marquesas Islands');
INSERT INTO `bc_countries` VALUES ('10125', '258', 'PF', 'Moorea');
INSERT INTO `bc_countries` VALUES ('10126', '258', 'PF', 'Nukahiva');
INSERT INTO `bc_countries` VALUES ('10127', '258', 'PF', 'Raiatea');
INSERT INTO `bc_countries` VALUES ('10128', '258', 'PF', 'Rapa');
INSERT INTO `bc_countries` VALUES ('10129', '258', 'PF', 'Society Islands');
INSERT INTO `bc_countries` VALUES ('10130', '258', 'PF', 'Tahaa');
INSERT INTO `bc_countries` VALUES ('10131', '258', 'PF', 'Tahiti');
INSERT INTO `bc_countries` VALUES ('10132', '258', 'PF', 'Tuamotou');
INSERT INTO `bc_countries` VALUES ('10133', '258', 'PF', 'Tubuai');
INSERT INTO `bc_countries` VALUES ('10345', '598', 'PG', 'Admiralty Islands');
INSERT INTO `bc_countries` VALUES ('10346', '598', 'PG', 'Bismark Archipelago');
INSERT INTO `bc_countries` VALUES ('10347', '598', 'PG', 'Bougainville');
INSERT INTO `bc_countries` VALUES ('10348', '598', 'PG', 'Buka');
INSERT INTO `bc_countries` VALUES ('10349', '598', 'PG', 'New Britain');
INSERT INTO `bc_countries` VALUES ('10350', '598', 'PG', 'New Hanover');
INSERT INTO `bc_countries` VALUES ('10351', '598', 'PG', 'New Ireland');
INSERT INTO `bc_countries` VALUES ('10352', '598', 'PG', 'Papua New Guinea');
INSERT INTO `bc_countries` VALUES ('10355', '608', 'PH', 'Philippines');
INSERT INTO `bc_countries` VALUES ('10342', '586', 'PK', 'Baluchistan');
INSERT INTO `bc_countries` VALUES ('10343', '586', 'PK', 'Pakistan');
INSERT INTO `bc_countries` VALUES ('10357', '616', 'PL', 'Poland');
INSERT INTO `bc_countries` VALUES ('10404', '666', 'PM', 'Miquelon');
INSERT INTO `bc_countries` VALUES ('10405', '666', 'PM', 'Saint Pierre and Miquelon');
INSERT INTO `bc_countries` VALUES ('10356', '612', 'PN', 'Pitcairn Island');
INSERT INTO `bc_countries` VALUES ('10359', '620', 'PT', 'Azores');
INSERT INTO `bc_countries` VALUES ('10360', '620', 'PT', 'Madeira Islands');
INSERT INTO `bc_countries` VALUES ('10362', '620', 'PT', 'Portugal');
INSERT INTO `bc_countries` VALUES ('10353', '600', 'PY', 'Paraguay');
INSERT INTO `bc_countries` VALUES ('10363', '634', 'QA', 'Doha');
INSERT INTO `bc_countries` VALUES ('10364', '634', 'QA', 'Qatar');
INSERT INTO `bc_countries` VALUES ('10365', '634', 'QA', 'Umm Said');
INSERT INTO `bc_countries` VALUES ('10366', '638', 'RE', 'Bourbon');
INSERT INTO `bc_countries` VALUES ('10367', '638', 'RE', 'Reunion');
INSERT INTO `bc_countries` VALUES ('10368', '642', 'RO', 'Romania');
INSERT INTO `bc_countries` VALUES ('12314', '25', 'RS', 'Republic of Kosovo');
INSERT INTO `bc_countries` VALUES ('10369', '643', 'RU', 'Russia');
INSERT INTO `bc_countries` VALUES ('10370', '646', 'RW', 'Rwanda');
INSERT INTO `bc_countries` VALUES ('10373', '682', 'SA', 'Saudi Arabia');
INSERT INTO `bc_countries` VALUES ('10381', '90', 'SB', 'Santa Cruz Islands');
INSERT INTO `bc_countries` VALUES ('10382', '90', 'SB', 'Solomon Islands');
INSERT INTO `bc_countries` VALUES ('10376', '690', 'SC', 'Seychelles');
INSERT INTO `bc_countries` VALUES ('10408', '736', 'SD', 'Sudan');
INSERT INTO `bc_countries` VALUES ('10411', '752', 'SE', 'Sweden');
INSERT INTO `bc_countries` VALUES ('10378', '702', 'SG', 'Singapore');
INSERT INTO `bc_countries` VALUES ('10402', '654', 'SH', 'Saint Helena');
INSERT INTO `bc_countries` VALUES ('10380', '705', 'SI', 'Slovenia');
INSERT INTO `bc_countries` VALUES ('10379', '703', 'SK', 'Slovak Republic');
INSERT INTO `bc_countries` VALUES ('10377', '694', 'SL', 'Sierra Leone');
INSERT INTO `bc_countries` VALUES ('10371', '674', 'SM', 'San Marino');
INSERT INTO `bc_countries` VALUES ('10374', '686', 'SN', 'Senegal');
INSERT INTO `bc_countries` VALUES ('10383', '706', 'SO', 'Somali Democratic Republic');
INSERT INTO `bc_countries` VALUES ('10384', '706', 'SO', 'Somalia');
INSERT INTO `bc_countries` VALUES ('10385', '706', 'SO', 'Somaliland');
INSERT INTO `bc_countries` VALUES ('10409', '740', 'SR', 'Suriname');
INSERT INTO `bc_countries` VALUES ('10372', '678', 'ST', 'Sao Tome and Principe');
INSERT INTO `bc_countries` VALUES ('10095', '222', 'SV', 'El Salvador');
INSERT INTO `bc_countries` VALUES ('10096', '222', 'SV', 'Salvador');
INSERT INTO `bc_countries` VALUES ('10413', '760', 'SY', 'Syrian Arab Republic');
INSERT INTO `bc_countries` VALUES ('10410', '748', 'SZ', 'Swaziland');
INSERT INTO `bc_countries` VALUES ('10434', '796', 'TC', 'Caicos Islands');
INSERT INTO `bc_countries` VALUES ('10435', '796', 'TC', 'Turks and Caicos Islands');
INSERT INTO `bc_countries` VALUES ('10060', '148', 'TD', 'Chad');
INSERT INTO `bc_countries` VALUES ('10061', '148', 'TD', 'Tchad');
INSERT INTO `bc_countries` VALUES ('10425', '768', 'TG', 'Togo');
INSERT INTO `bc_countries` VALUES ('10423', '764', 'TH', 'Siam');
INSERT INTO `bc_countries` VALUES ('10424', '764', 'TH', 'Thailand');
INSERT INTO `bc_countries` VALUES ('10419', '762', 'TJ', 'Tajikistan');
INSERT INTO `bc_countries` VALUES ('10509', '772', 'TK', 'Tokelau');
INSERT INTO `bc_countries` VALUES ('10201', '626', 'TL', 'East Timor');
INSERT INTO `bc_countries` VALUES ('10433', '795', 'TM', 'Turkmenistan');
INSERT INTO `bc_countries` VALUES ('10431', '788', 'TN', 'Tunisia');
INSERT INTO `bc_countries` VALUES ('10426', '776', 'TO', 'Friendly Islands');
INSERT INTO `bc_countries` VALUES ('10427', '776', 'TO', 'Tonga');
INSERT INTO `bc_countries` VALUES ('10432', '792', 'TR', 'Turkey');
INSERT INTO `bc_countries` VALUES ('10428', '780', 'TT', 'Tobago');
INSERT INTO `bc_countries` VALUES ('10429', '780', 'TT', 'Trinidad and Tobago');
INSERT INTO `bc_countries` VALUES ('10436', '798', 'TV', 'Ellice Islands');
INSERT INTO `bc_countries` VALUES ('10437', '798', 'TV', 'Tuvalu');
INSERT INTO `bc_countries` VALUES ('10414', '158', 'TW', 'Formosa');
INSERT INTO `bc_countries` VALUES ('10415', '158', 'TW', 'Penghu Islands');
INSERT INTO `bc_countries` VALUES ('10416', '158', 'TW', 'Pescadores Islands');
INSERT INTO `bc_countries` VALUES ('10417', '158', 'TW', 'Quemoy');
INSERT INTO `bc_countries` VALUES ('10418', '158', 'TW', 'Taiwan');
INSERT INTO `bc_countries` VALUES ('10420', '834', 'TZ', 'Pemba');
INSERT INTO `bc_countries` VALUES ('10421', '834', 'TZ', 'Tanzania');
INSERT INTO `bc_countries` VALUES ('10422', '834', 'TZ', 'Zanzibar');
INSERT INTO `bc_countries` VALUES ('10439', '804', 'UA', 'Ukraine');
INSERT INTO `bc_countries` VALUES ('10438', '800', 'UG', 'Uganda');
INSERT INTO `bc_countries` VALUES ('1', '840', 'US', 'United States');
INSERT INTO `bc_countries` VALUES ('12023', '840', 'US', 'Virgin Islands');
INSERT INTO `bc_countries` VALUES ('10495', '860', 'UZ', 'Uzbekistan');
INSERT INTO `bc_countries` VALUES ('10500', '336', 'VA', 'Vatican City');
INSERT INTO `bc_countries` VALUES ('10407', '670', 'VC', 'Grenadines');
INSERT INTO `bc_countries` VALUES ('10501', '862', 'VE', 'Venezuela');
INSERT INTO `bc_countries` VALUES ('10044', '92', 'VG', 'British Virgin Islands');
INSERT INTO `bc_countries` VALUES ('10502', '704', 'VN', 'Vietnam');
INSERT INTO `bc_countries` VALUES ('10496', '548', 'VU', 'Banks Island');
INSERT INTO `bc_countries` VALUES ('10497', '548', 'VU', 'New Hebrides');
INSERT INTO `bc_countries` VALUES ('10498', '548', 'VU', 'Torres Island');
INSERT INTO `bc_countries` VALUES ('10499', '548', 'VU', 'Vanuatu');
INSERT INTO `bc_countries` VALUES ('10503', '876', 'WF', 'Futuna');
INSERT INTO `bc_countries` VALUES ('10504', '876', 'WF', 'Wallis and Futuna Islands');
INSERT INTO `bc_countries` VALUES ('10505', '882', 'WS', 'Atafu');
INSERT INTO `bc_countries` VALUES ('10506', '882', 'WS', 'Fakaofo');
INSERT INTO `bc_countries` VALUES ('10507', '882', 'WS', 'Nukunonu');
INSERT INTO `bc_countries` VALUES ('10508', '882', 'WS', 'Savaii Island');
INSERT INTO `bc_countries` VALUES ('10510', '882', 'WS', 'Union Group');
INSERT INTO `bc_countries` VALUES ('10511', '882', 'WS', 'Upolu Island');
INSERT INTO `bc_countries` VALUES ('10512', '882', 'WS', 'Western Samoa');
INSERT INTO `bc_countries` VALUES ('10513', '887', 'YE', 'Yemen');
INSERT INTO `bc_countries` VALUES ('10115', '175', 'YT', 'Mayotte');
INSERT INTO `bc_countries` VALUES ('10386', '710', 'ZA', 'South Africa');
INSERT INTO `bc_countries` VALUES ('10387', '710', 'ZA', 'Transkei');
INSERT INTO `bc_countries` VALUES ('10514', '894', 'ZM', 'Zambia');
INSERT INTO `bc_countries` VALUES ('10515', '716', 'ZW', 'Rhodesia');
INSERT INTO `bc_countries` VALUES ('10516', '716', 'ZW', 'Zimbabwe');
INSERT INTO `bc_countries` VALUES ('10233', '408', 'KP', 'North Korea (Democratic People''s Republic of Korea)');